In [2]:
import pandas as pd
from fuzzywuzzy import fuzz
from fuzzywuzzy import process
import fuzzymatcher

In [2]:
df1 = pd.read_csv('/home/jklingl/Downloads/pssdb.csv')
df2 = pd.read_csv('/home/jklingl/Downloads/schools.csv')

# trying from scracth below

In [28]:
import fuzzymatcher

In [61]:
df2.columns

Index(['School Name', 'State Name [Public School] Latest available year',
       'State Abbr [Public School] Latest available year',
       'School ID - NCES Assigned [Public School] Latest available year',
       'Agency Name [Public School] 2019-20',
       'School Type [Public School] 2019-20',
       'Charter School [Public School] 2019-20',
       'Magnet School [Public School] 2019-20',
       'Shared Time School [Public School] 2019-20',
       'Urban-centric Locale [Public School] 2019-20',
       'Total Students All Grades (Excludes AE) [Public School] 2019-20',
       'Full-Time Equivalent (FTE) Teachers [Public School] 2019-20',
       'Pupil/Teacher Ratio [Public School] 2019-20',
       'Lowest Grade Offered [Public School] 2019-20',
       'Highest Grade Offered [Public School] 2019-20',
       'School Level (SY 2017-18 onward) [Public School] 2019-20'],
      dtype='object')

In [5]:
left_on = ['State','School']
right_on = ['State Abbr [Public School] Latest available year', 'School Name']
df_fuz_merge = fuzzymatcher.fuzzy_left_join(df1,df2,left_on,right_on)

In [12]:
left_on = ['School','State']
right_on = ['School Name','State Abbr [Public School] Latest available year']
df_fuz_merge2 = fuzzymatcher.fuzzy_left_join(df1,df2,left_on,right_on)

In [13]:
df_fuz_merge2[cols]

,best_match_score,School Name,School,State,State Abbr [Public School] Latest available year,__id_left,__id_right,Incident_ID,Month,Day,...,School ID - NCES Assigned [Public School] Latest available year,Agency Name [Public School] 2019-20,School Type [Public School] 2019-20,Charter School [Public School] 2019-20,Magnet School [Public School] 2019-20,Shared Time School [Public School] 2019-20,Urban-centric Locale [Public School] 2019-20,Total Students All Grades (Excludes AE) [Public School] 2019-20,Full-Time Equivalent (FTE) Teachers [Public School] 2019-20,Pupil/Teacher Ratio [Public School] 2019-20
0,0.853121,KIPP INDY LEGACY HIGH,Kipp Indy Legacy High School,IN,IN,0_left,46593_right,20231103INKII,11,3,...,1.800210e+11,KIPP Indy Legacy High,1-Regular school,1-Yes,2-No,2-No,11-City: Large,125,9,13.89
140,0.053424,COMMUNITY HIGH SCHOOL,Freedom High School,NC,NC,1_left,17773_right,20231102NCFRM,11,2,...,3.700450e+11,Buncombe County Schools,4-Alternative/other school,2-No,2-No,2-No,21-Suburb: Large,122,17.93,6.8
190,0.496949,WASHINGTON ELEMENTARY SCHOOL,Washington Elementary School,OH,OH,2_left,93231_right,20231102OHWAL,11,2,...,3.904430e+11,Lorain City,1-Regular school,2-No,–,2-No,22-Suburb: Mid-size,268,16.8,15.95
201,0.120393,RALEIGH CHARTER HIGH SCHOOL,Raleigh School Bus,NC,NC,3_left,72981_right,20231030NCRAR,10,30,...,3.700100e+11,Raleigh Charter High School,1-Regular school,1-Yes,2-No,2-No,11-City: Large,562,40.44,13.9
202,-0.311320,FARRIS EARLY CHILDHOOD CTR,Dub Farris Athletic Complex,TX,TX,4_left,28409_right,20231027TXDUS,10,27,...,4.845780e+11,WICHITA FALLS ISD,1-Regular school,2-No,2-No,–,12-City: Mid-size,236,17,13.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157621,0.582133,BAY SHORE SENIOR HIGH SCHOOL,Bay Shore High School,NY,NY,2579_left,5482_right,19660427NYBAB,4,27,...,3.604080e+11,BAY SHORE UNION FREE SCHOOL DISTRICT,1-Regular school,2-No,2-No,2-No,21-Suburb: Large,1956,167.2,11.7
157622,0.484839,JORDAN HIGH,Jordan High School,CA,CA,2580_left,44643_right,19660328CAJOL,3,28,...,6.225000e+10,Long Beach Unified,1-Regular school,2-No,1-Yes,–,11-City: Large,2380,–,†
157736,0.023566,CAMINO NUEVO ELEMENTARY SCHOOL #3,Camino Pablo Elementary School,CA,CA,2581_left,11554_right,19660324CACAM,3,24,...,6.020771e+10,Camino Nuevo Elementary School #3 District,1-Regular school,1-Yes,2-No,–,11-City: Large,766,–,†
157737,0.290635,CARVER HIGH SCHOOL,Carver High School,TX,GA,2582_left,12682_right,19660314TXCAW,3,14,...,1.303870e+11,Muscogee County,1-Regular school,2-No,2-No,2-No,12-City: Mid-size,871,66.2,13.16
157855,0.202209,FOURTH AVENUE JUNIOR HIGH SCHOOL,Irwing Avenue Junior High School,NC,AZ,2583_left,29889_right,19660311NCIRC,3,11,...,4.096000e+10,Yuma Elementary District (4499),1-Regular school,2-No,–,2-No,13-City: Small,452,23.5,19.23

In [15]:
fuxmatch3 = fuzzymatcher.fuzzy_left_join(df1, df2, left_on, right_on)

In [34]:
# had to strip extra spaces on schools df
fuxmatch3['State Abbr [Public School] Latest available year'] = fuxmatch3['State Abbr [Public School] Latest available year'].str.replace(' ', '')

In [35]:
# showing the rows that correctly match state
matching_rows = fuxmatch3[fuxmatch3['State'] == fuxmatch3['State Abbr [Public School] Latest available year']]

In [42]:
# correct df by getting rows that had best matches
# should check row by row to make sure they all correct
# also try lowering the .5 value to maybe get more data
correctly_matched_df = fuxmatch3[fuxmatch3['best_match_score']>.5][cols]

# matched df correctly

In [ ]:
correctly_matched_df.to_csv('correctly_matched_df.csv', index=False)

# final-df

In [37]:
fuxmatch3[fuxmatch3['State'] == fuxmatch3['State Abbr [Public School] Latest available year']][cols]

,best_match_score,School Name,School,State,State Abbr [Public School] Latest available year,__id_left,__id_right,Incident_ID,Month,Day,...,School ID - NCES Assigned [Public School] Latest available year,Agency Name [Public School] 2019-20,School Type [Public School] 2019-20,Charter School [Public School] 2019-20,Magnet School [Public School] 2019-20,Shared Time School [Public School] 2019-20,Urban-centric Locale [Public School] 2019-20,Total Students All Grades (Excludes AE) [Public School] 2019-20,Full-Time Equivalent (FTE) Teachers [Public School] 2019-20,Pupil/Teacher Ratio [Public School] 2019-20
0,0.853121,KIPP INDY LEGACY HIGH,Kipp Indy Legacy High School,IN,IN,0_left,46593_right,20231103INKII,11,3,...,1.800210e+11,KIPP Indy Legacy High,1-Regular school,1-Yes,2-No,2-No,11-City: Large,125,9,13.89
140,0.053424,COMMUNITY HIGH SCHOOL,Freedom High School,NC,NC,1_left,17773_right,20231102NCFRM,11,2,...,3.700450e+11,Buncombe County Schools,4-Alternative/other school,2-No,2-No,2-No,21-Suburb: Large,122,17.93,6.8
190,0.496949,WASHINGTON ELEMENTARY SCHOOL,Washington Elementary School,OH,OH,2_left,93231_right,20231102OHWAL,11,2,...,3.904430e+11,Lorain City,1-Regular school,2-No,–,2-No,22-Suburb: Mid-size,268,16.8,15.95
201,0.120393,RALEIGH CHARTER HIGH SCHOOL,Raleigh School Bus,NC,NC,3_left,72981_right,20231030NCRAR,10,30,...,3.700100e+11,Raleigh Charter High School,1-Regular school,1-Yes,2-No,2-No,11-City: Large,562,40.44,13.9
202,-0.311320,FARRIS EARLY CHILDHOOD CTR,Dub Farris Athletic Complex,TX,TX,4_left,28409_right,20231027TXDUS,10,27,...,4.845780e+11,WICHITA FALLS ISD,1-Regular school,2-No,2-No,–,12-City: Mid-size,236,17,13.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157384,0.463158,SOUTH PHILADELPHIA HS,South Philadelphia High School,PA,PA,2577_left,82465_right,19660922PAPHP,9,22,...,4.218990e+11,Philadelphia City SD,1-Regular school,2-No,2-No,2-No,11-City: Large,643,39.95,16.1
157488,0.510038,SEMINOLE HIGH SCHOOL,Seminole High School,FL,FL,2578_left,79706_right,19660828FLSEC,8,28,...,1.201560e+11,PINELLAS,1-Regular school,2-No,1-Yes,2-No,21-Suburb: Large,1759,82,21.45
157493,0.582133,BAY SHORE SENIOR HIGH SCHOOL,Bay Shore High School,NY,NY,2579_left,5482_right,19660427NYBAB,4,27,...,3.604080e+11,BAY SHORE UNION FREE SCHOOL DISTRICT,1-Regular school,2-No,2-No,2-No,21-Suburb: Large,1956,167.2,11.7
157494,0.484839,JORDAN HIGH,Jordan High School,CA,CA,2580_left,44643_right,19660328CAJOL,3,28,...,6.225000e+10,Long Beach Unified,1-Regular school,2-No,1-Yes,–,11-City: Large,2380,–,†
157608,0.023566,CAMINO NUEVO ELEMENTARY SCHOOL #3,Camino Pablo Elementary School,CA,CA,2581_left,11554_right,19660324CACAM,3,24,...,6.020771e+10,Camino Nuevo Elementary School #3 District,1-Regular school,1-Yes,2-No,–,11-City: Large,766,–,†

In [24]:
fuxmatch3[cols]

,best_match_score,School Name,School,State,State Abbr [Public School] Latest available year,__id_left,__id_right,Incident_ID,Month,Day,...,School ID - NCES Assigned [Public School] Latest available year,Agency Name [Public School] 2019-20,School Type [Public School] 2019-20,Charter School [Public School] 2019-20,Magnet School [Public School] 2019-20,Shared Time School [Public School] 2019-20,Urban-centric Locale [Public School] 2019-20,Total Students All Grades (Excludes AE) [Public School] 2019-20,Full-Time Equivalent (FTE) Teachers [Public School] 2019-20,Pupil/Teacher Ratio [Public School] 2019-20
0,0.853121,KIPP INDY LEGACY HIGH,Kipp Indy Legacy High School,IN,IN,0_left,46593_right,20231103INKII,11,3,...,1.800210e+11,KIPP Indy Legacy High,1-Regular school,1-Yes,2-No,2-No,11-City: Large,125,9,13.89
140,0.053424,COMMUNITY HIGH SCHOOL,Freedom High School,NC,NC,1_left,17773_right,20231102NCFRM,11,2,...,3.700450e+11,Buncombe County Schools,4-Alternative/other school,2-No,2-No,2-No,21-Suburb: Large,122,17.93,6.8
190,0.496949,WASHINGTON ELEMENTARY SCHOOL,Washington Elementary School,OH,OH,2_left,93231_right,20231102OHWAL,11,2,...,3.904430e+11,Lorain City,1-Regular school,2-No,–,2-No,22-Suburb: Mid-size,268,16.8,15.95
201,0.120393,RALEIGH CHARTER HIGH SCHOOL,Raleigh School Bus,NC,NC,3_left,72981_right,20231030NCRAR,10,30,...,3.700100e+11,Raleigh Charter High School,1-Regular school,1-Yes,2-No,2-No,11-City: Large,562,40.44,13.9
202,-0.311320,FARRIS EARLY CHILDHOOD CTR,Dub Farris Athletic Complex,TX,TX,4_left,28409_right,20231027TXDUS,10,27,...,4.845780e+11,WICHITA FALLS ISD,1-Regular school,2-No,2-No,–,12-City: Mid-size,236,17,13.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157493,0.582133,BAY SHORE SENIOR HIGH SCHOOL,Bay Shore High School,NY,NY,2579_left,5482_right,19660427NYBAB,4,27,...,3.604080e+11,BAY SHORE UNION FREE SCHOOL DISTRICT,1-Regular school,2-No,2-No,2-No,21-Suburb: Large,1956,167.2,11.7
157494,0.484839,JORDAN HIGH,Jordan High School,CA,CA,2580_left,44643_right,19660328CAJOL,3,28,...,6.225000e+10,Long Beach Unified,1-Regular school,2-No,1-Yes,–,11-City: Large,2380,–,†
157608,0.023566,CAMINO NUEVO ELEMENTARY SCHOOL #3,Camino Pablo Elementary School,CA,CA,2581_left,11554_right,19660324CACAM,3,24,...,6.020771e+10,Camino Nuevo Elementary School #3 District,1-Regular school,1-Yes,2-No,–,11-City: Large,766,–,†
157609,0.290635,CARVER HIGH SCHOOL,Carver High School,TX,GA,2582_left,12682_right,19660314TXCAW,3,14,...,1.303870e+11,Muscogee County,1-Regular school,2-No,2-No,2-No,12-City: Mid-size,871,66.2,13.16
157727,0.202209,FOURTH AVENUE JUNIOR HIGH SCHOOL,Irwing Avenue Junior High School,NC,AZ,2583_left,29889_right,19660311NCIRC,3,11,...,4.096000e+10,Yuma Elementary District (4499),1-Regular school,2-No,–,2-No,13-City: Small,452,23.5,19.23

In [7]:
cols = ['best_match_score', 'School Name','School','State','State Abbr [Public School] Latest available year','__id_left', '__id_right', 'Incident_ID', 'Month',
       'Day', 'Year', 'Date', 'School', 'Victims_Killed', 'Victims_Wounded',
       'Number_Victims', 'Shooter_Killed', 'Source', 'Number_News',
       'Media_Attention', 'Reliability', 'Quarter', 'City',
       'School_Level', 'Location', 'Location_Type', 'During_Classes',
       'Time_Period', 'First_Shot', 'Duration_min', 'Summary', 'Narrative',
       'Situation', 'Targets', 'Accomplice', 'Accomplice_Narrative',
       'Hostages', 'Barricade', 'Officer_Involved', 'Bullied',
       'Domestic_Violence', 'Gang_Related', 'Active_Shooter_FBI',
       'Shots_Fired', 'LAT', 'LNG',
       'State Name [Public School] Latest available year',
       'School ID - NCES Assigned [Public School] Latest available year',
       'Agency Name [Public School] 2019-20',
       'School Type [Public School] 2019-20',
       'Charter School [Public School] 2019-20',
       'Magnet School [Public School] 2019-20',
       'Shared Time School [Public School] 2019-20',
       'Urban-centric Locale [Public School] 2019-20',
       'Total Students All Grades (Excludes AE) [Public School] 2019-20',
       'Full-Time Equivalent (FTE) Teachers [Public School] 2019-20',
       'Pupil/Teacher Ratio [Public School] 2019-20']

In [18]:
df_fuz_merge[cols]

,best_match_score,Agency Name [Public School] 2019-20,School,State,State Abbr [Public School] Latest available year,__id_left,__id_right,Incident_ID,Month,Day,...,School ID - NCES Assigned [Public School] Latest available year,Agency Name [Public School] 2019-20,School Type [Public School] 2019-20,Charter School [Public School] 2019-20,Magnet School [Public School] 2019-20,Shared Time School [Public School] 2019-20,Urban-centric Locale [Public School] 2019-20,Total Students All Grades (Excludes AE) [Public School] 2019-20,Full-Time Equivalent (FTE) Teachers [Public School] 2019-20,Pupil/Teacher Ratio [Public School] 2019-20
0,0.737670,KIPP Indy Legacy High,Kipp Indy Legacy High School,IN,IN,0_left,46593_right,20231103INKII,11,3,...,1.800210e+11,KIPP Indy Legacy High,1-Regular school,1-Yes,2-No,2-No,11-City: Large,125,9,13.89
97,0.388349,HILLSBOROUGH,Freedom High School,NC,FL,1_left,30673_right,20231102NCFRM,11,2,...,1.200870e+11,HILLSBOROUGH,1-Regular school,2-No,2-No,2-No,11-City: Large,1811,103.5,17.5
100,0.414278,Lorain City,Washington Elementary School,OH,OH,2_left,93231_right,20231102OHWAL,11,2,...,3.904430e+11,Lorain City,1-Regular school,2-No,–,2-No,22-Suburb: Mid-size,268,16.8,15.95
150,0.095592,SMITH CO SCHOOL DIST,Raleigh School Bus,NC,MS,3_left,72983_right,20231030NCRAR,10,30,...,2.804020e+11,SMITH CO SCHOOL DIST,1-Regular school,2-No,2-No,2-No,43-Rural: Remote,589,33.67,17.49
156,-0.250256,School District No. 1 in the county of Denver ...,Dub Farris Athletic Complex,TX,CO,4_left,32622_right,20231027TXDUS,10,27,...,8.033601e+10,School District No. 1 in the county of Denver ...,1-Regular school,1-Yes,2-No,2-No,11-City: Large,133,9.36,14.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83208,0.497624,BAY SHORE UNION FREE SCHOOL DISTRICT,Bay Shore High School,NY,NY,2579_left,5482_right,19660427NYBAB,4,27,...,3.604080e+11,BAY SHORE UNION FREE SCHOOL DISTRICT,1-Regular school,2-No,2-No,2-No,21-Suburb: Large,1956,167.2,11.7
83209,0.513515,JORDAN PUBLIC SCHOOL DISTRICT,Jordan High School,CA,MN,2580_left,44645_right,19660328CAJOL,3,28,...,2.715750e+11,JORDAN PUBLIC SCHOOL DISTRICT,1-Regular school,2-No,2-No,2-No,31-Town: Fringe,599,34.68,17.27
83215,0.593599,Moraga Elementary,Camino Pablo Elementary School,CA,CA,2581_left,11557_right,19660324CACAM,3,24,...,6.257400e+10,Moraga Elementary,1-Regular school,2-No,2-No,–,21-Suburb: Large,349,–,†
83299,0.379173,Muscogee County,Carver High School,TX,GA,2582_left,12682_right,19660314TXCAW,3,14,...,1.303870e+11,Muscogee County,1-Regular school,2-No,2-No,2-No,12-City: Mid-size,871,66.2,13.16
83307,0.308168,Yuma Elementary District (4499),Irwing Avenue Junior High School,NC,AZ,2583_left,29889_right,19660311NCIRC,3,11,...,4.096000e+10,Yuma Elementary District (4499),1-Regular school,2-No,–,2-No,13-City: Small,452,23.5,19.23

In [16]:
df_fuz_merge.sort_values(by=['best_match_score'])[cols].tail()

,best_match_score,Agency Name [Public School] 2019-20,School,State,State Abbr [Public School] Latest available year,__id_left,__id_right,Incident_ID,Month,Day,...,School ID - NCES Assigned [Public School] Latest available year,Agency Name [Public School] 2019-20,School Type [Public School] 2019-20,Charter School [Public School] 2019-20,Magnet School [Public School] 2019-20,Shared Time School [Public School] 2019-20,Urban-centric Locale [Public School] 2019-20,Total Students All Grades (Excludes AE) [Public School] 2019-20,Full-Time Equivalent (FTE) Teachers [Public School] 2019-20,Pupil/Teacher Ratio [Public School] 2019-20
63253,1.338249,Colorado Springs School District No. 11 in the...,Jack Swigert Aerospace Academy,CO,CO,1049_left,42380_right,20190629COJAC,6,29,...,8.030601e+10,Colorado Springs School District No. 11 in the...,1-Regular school,2-No,2-No,2-No,11-City: Large,578,41,14.1
53702,1.357150,Portland SD 1J,Dr. Martin Luther King Jr. Elementary School,OR,OR,909_left,22857_right,20200917ORDRP,9,17,...,4.110040e+11,Portland SD 1J,1-Regular school,2-No,†,–,11-City: Large,321,22.2,14.46
94096,1.422524,Cincinnati Public Schools,Robert A. Taft Information Technology High School,OH,OH,1606_left,75531_right,20070108OHROC,1,8,...,3.904380e+11,Cincinnati Public Schools,1-Regular school,2-No,–,2-No,11-City: Large,668,70.4,9.49
29272,1.467854,Milwaukee School District,Wisconsin Conservatory of Lifelong Learning,WI,WI,503_left,97896_right,20220425WIWIM,4,25,...,5.509600e+11,Milwaukee School District,1-Regular school,2-No,2-No,2-No,11-City: Large,408,31,13.16
67455,1.765929,NEW YORK CITY GEOGRAPHIC DISTRICT #10,Luisa Pineiro Fuentes School of Science and Di...,NY,NY,1145_left,52444_right,20180903NYLUN,9,3,...,3.600090e+11,NEW YORK CITY GEOGRAPHIC DISTRICT #10,1-Regular school,2-No,2-No,2-No,11-City: Large,298,25,11.92

In [44]:
irp_df = pd.read_csv('/home/jklingl/Downloads/EDGE_SIDE1721_PUBSCHS2021.csv')

In [71]:
irp_df.columns

Index(['NCESSCH', 'NAME', 'IPR_EST', 'IPR_SE'], dtype='object')

In [72]:
cols2 = ['Incident_ID', 'NAME', 'School','Month', 'Day', 'Year', 'Date',
       'Victims_Killed', 'Victims_Wounded', 'Number_Victims', 'Shooter_Killed',
       'Source', 'Number_News', 'Media_Attention', 'Reliability', 'Quarter',
       'City', 'State', 'School_Level', 'Location', 'Location_Type',
       'During_Classes', 'Time_Period', 'First_Shot', 'Duration_min',
       'Summary', 'Narrative', 'Situation', 'Targets', 'Accomplice',
       'Accomplice_Narrative', 'Hostages', 'Barricade', 'Officer_Involved',
       'Bullied', 'Domestic_Violence', 'Gang_Related', 'Active_Shooter_FBI',
       'Shots_Fired', 'LAT', 'LNG','NCESSCH', 'IPR_EST', 'IPR_SE']

In [73]:
left_on = ['School']
right_on = ['NAME']
df_irp_matched = fuzzymatcher.fuzzy_left_join(df1,irp_df,left_on,right_on)

# matched df for IRP

In [74]:
irp_matched = df_irp_matched[df_irp_matched['best_match_score']>.5][cols2]

In [75]:
irp_matched.columns

Index(['Incident_ID', 'NAME', 'School', 'Month', 'Day', 'Year', 'Date',
       'Victims_Killed', 'Victims_Wounded', 'Number_Victims', 'Shooter_Killed',
       'Source', 'Number_News', 'Media_Attention', 'Reliability', 'Quarter',
       'City', 'State', 'School_Level', 'Location', 'Location_Type',
       'During_Classes', 'Time_Period', 'First_Shot', 'Duration_min',
       'Summary', 'Narrative', 'Situation', 'Targets', 'Accomplice',
       'Accomplice_Narrative', 'Hostages', 'Barricade', 'Officer_Involved',
       'Bullied', 'Domestic_Violence', 'Gang_Related', 'Active_Shooter_FBI',
       'Shots_Fired', 'LAT', 'LNG', 'NCESSCH', 'IPR_EST', 'IPR_SE'],
      dtype='object')

In [76]:
irp_matched.to_csv('irp_matched_df.csv', index=False)

In [81]:
irp_copy = irp_matched.copy(deep = True)

In [82]:
correctly_matched_copy = correctly_matched_df.copy(deep = True)

In [78]:
correctly_matched_df.sort_values(by=['best_match_score'])

,best_match_score,School Name,School,State,State Abbr [Public School] Latest available year,__id_left,__id_right,Incident_ID,Month,Day,...,School ID - NCES Assigned [Public School] Latest available year,Agency Name [Public School] 2019-20,School Type [Public School] 2019-20,Charter School [Public School] 2019-20,Magnet School [Public School] 2019-20,Shared Time School [Public School] 2019-20,Urban-centric Locale [Public School] 2019-20,Total Students All Grades (Excludes AE) [Public School] 2019-20,Full-Time Equivalent (FTE) Teachers [Public School] 2019-20,Pupil/Teacher Ratio [Public School] 2019-20
54599,0.500221,SOUTHMAYD EL,Southmayd Elementary School,TX,TX,917_left,82948_right,20200909TXSOH,9,9,...,4.823640e+11,HOUSTON ISD,1-Regular school,2-No,2-No,–,11-City: Large,565,34.94,16.17
71014,0.500319,PATTENGILL SCHOOL,Pattengill Academy,MI,MI,1235_left,67834_right,20171103MIPAL,11,3,...,2.602820e+11,Ann Arbor Public Schools,1-Regular school,2-No,2-No,2-No,12-City: Mid-size,253,20.9,12.11
72176,0.500544,WILSON HIGH,Wilson High School,SC,SC,1254_left,97428_right,20170622SCWIF,6,22,...,4.502130e+11,Florence 01,1-Regular school,2-No,2-No,2-No,41-Rural: Fringe,1173,94,12.48
117470,0.501533,HUBBARD HIGH SCHOOL,Hubbard High School,IL,IL,1991_left,40205_right,19941017ILHUC,10,17,...,1.709930e+11,City of Chicago SD 299,1-Regular school,2-No,2-No,2-No,11-City: Large,1626,106.5,15.27
34317,0.502324,CARROLL HIGH SCHOOL,Carroll High School,LA,LA,591_left,12488_right,20220128LACAM,1,28,...,2.201080e+11,City of Monroe School District,1-Regular school,2-No,2-No,–,13-City: Small,584,34.06,17.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63278,1.338249,JACK SWIGERT AEROSPACE ACADEMY,Jack Swigert Aerospace Academy,CO,CO,1049_left,42380_right,20190629COJAC,6,29,...,8.030601e+10,Colorado Springs School District No. 11 in the...,1-Regular school,2-No,2-No,2-No,11-City: Large,578,41,14.1
53729,1.357150,DR. MARTIN LUTHER KING JR. SCHOOL,Dr. Martin Luther King Jr. Elementary School,OR,OR,909_left,22857_right,20200917ORDRP,9,17,...,4.110040e+11,Portland SD 1J,1-Regular school,2-No,†,–,11-City: Large,321,22.2,14.46
94067,1.422524,ROBERT A. TAFT INFORMATION TECHNOLOGY HIGH SCHOOL,Robert A. Taft Information Technology High School,OH,OH,1606_left,75531_right,20070108OHROC,1,8,...,3.904380e+11,Cincinnati Public Schools,1-Regular school,2-No,–,2-No,11-City: Large,668,70.4,9.49
29319,1.467854,WISCONSIN CONSERVATORY OF LIFELONG LEARNING,Wisconsin Conservatory of Lifelong Learning,WI,WI,503_left,97896_right,20220425WIWIM,4,25,...,5.509600e+11,Milwaukee School District,1-Regular school,2-No,2-No,2-No,11-City: Large,408,31,13.16
67480,1.765929,LUISA PINEIRO FUENTES SCHOOL OF SCIENCE AND DI...,Luisa Pineiro Fuentes School of Science and Di...,NY,NY,1145_left,52444_right,20180903NYLUN,9,3,...,3.600090e+11,NEW YORK CITY GEOGRAPHIC DISTRICT #10,1-Regular school,2-No,2-No,2-No,11-City: Large,298,25,11.92

In [91]:
correctly_matched_copy.columns

Index(['best_match_score', 'School Name', 'School', 'State',
       'State Abbr [Public School] Latest available year', '__id_left',
       '__id_right', 'Incident_ID', 'Month', 'Day', 'Year', 'Date', 'School',
       'Victims_Killed', 'Victims_Wounded', 'Number_Victims', 'Shooter_Killed',
       'Source', 'Number_News', 'Media_Attention', 'Reliability', 'Quarter',
       'City', 'School_Level', 'Location', 'Location_Type', 'During_Classes',
       'Time_Period', 'First_Shot', 'Duration_min', 'Summary', 'Narrative',
       'Situation', 'Targets', 'Accomplice', 'Accomplice_Narrative',
       'Hostages', 'Barricade', 'Officer_Involved', 'Bullied',
       'Domestic_Violence', 'Gang_Related', 'Active_Shooter_FBI',
       'Shots_Fired', 'LAT', 'LNG',
       'State Name [Public School] Latest available year',
       'School ID - NCES Assigned [Public School] Latest available year',
       'Agency Name [Public School] 2019-20',
       'School Type [Public School] 2019-20',
       'Charter School [Public School] 2019-20',
       'Magnet School [Public School] 2019-20',
       'Shared Time School [Public School] 2019-20',
       'Urban-centric Locale [Public School] 2019-20',
       'Total Students All Grades (Excludes AE) [Public School] 2019-20',
       'Full-Time Equivalent (FTE) Teachers [Public School] 2019-20',
       'Pupil/Teacher Ratio [Public School] 2019-20'],
      dtype='object')

In [2]:
irp_data = pd.read_csv('/home/jklingl/capstone/irp_matched_df.csv')
school_data = pd.read_csv('/home/jklingl/capstone/correctly_matched_df.csv')

In [30]:
irp_data

,Incident_ID,NAME,School,Month,Day,Year,Date,Victims_Killed,Victims_Wounded,Number_Victims,...,Bullied,Domestic_Violence,Gang_Related,Active_Shooter_FBI,Shots_Fired,LAT,LNG,NCESSCH,IPR_EST,IPR_SE
0,20231103INKII,KIPP Indy Legacy High,Kipp Indy Legacy High School,11,3,2023,11/3/2023,1,0,1,...,No,No,NaN,No,99,39.798070,-86.130690,180020602669,196,66
1,20231019ILMAC,Mather High School,Mather High School,10,19,2023,10/19/2023,0,0,0,...,No,No,NaN,No,99,41.987506,-87.700849,170993000977,264,109
2,20231011FLMIM,MIAMI EDISON SENIOR HIGH SCHOOL,Miami Edison High School,10,11,2023,10/11/2023,1,0,1,...,No,No,Yes,No,99,25.831978,-80.204024,120039000600,166,68
3,20231008ILTHD,Thornridge High School,Thornridge High School,10,8,2023,10/8/2023,0,0,0,...,No,No,No,No,10,41.621601,-87.600081,173897003954,173,33
4,20231004COROD,Rocky Mountain Prep: Southwest,Rocky Mountain Prep Southwest,10,4,2023,10/4/2023,0,1,1,...,No,No,NaN,No,99,39.698913,-105.027691,80336006646,150,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
679,19671018PAGEP,GERMANTOWN HIGH SCHOOL,Germantown High School,10,18,1967,10/18/1967,0,2,2,...,No,No,Yes,No,5,40.039725,-75.176793,280279001381,557,87
680,19670503ILWEN,West Leyden High School,West Leyden High School,5,3,1967,5/3/1967,1,1,2,...,No,Yes,No,No,2,41.926364,-87.905440,172274002522,236,26
681,19661005MNGRG,East Grand Rapids High School,Grand Rapids High School,10,5,1966,10/5/1966,1,1,2,...,Yes,No,No,Yes,10,47.247714,-93.542248,261248004961,478,110
682,19660328CAJOL,Jordan High School,Jordan High School,3,28,1966,3/28/1966,0,1,1,...,No,No,No,No,99,33.944239,-118.230560,271575001625,469,62
683,19660324CACAM,Camino Pablo Elementary,Camino Pablo Elementary School,3,24,1966,3/24/1966,3,0,3,...,No,No,No,No,99,37.821031,-122.121426,62574003849,935,45

In [20]:
school_data.columns

Index(['best_match_score', 'School Name', 'School', 'State',
       'State Abbr [Public School] Latest available year', 'Incident_ID',
       'Month', 'Day', 'Year', 'Date', 'School.1', 'Victims_Killed',
       'Victims_Wounded', 'Number_Victims', 'Shooter_Killed', 'Source',
       'Number_News', 'Media_Attention', 'Reliability', 'Quarter', 'City',
       'School_Level', 'Location', 'Location_Type', 'During_Classes',
       'Time_Period', 'First_Shot', 'Duration_min', 'Summary', 'Narrative',
       'Situation', 'Targets', 'Accomplice', 'Accomplice_Narrative',
       'Hostages', 'Barricade', 'Officer_Involved', 'Bullied',
       'Domestic_Violence', 'Gang_Related', 'Active_Shooter_FBI',
       'Shots_Fired', 'LAT', 'LNG',
       'State Name [Public School] Latest available year',
       'School ID - NCES Assigned [Public School] Latest available year',
       'Agency Name [Public School] 2019-20',
       'School Type [Public School] 2019-20',
       'Charter School [Public School] 2019-20',
       'Magnet School [Public School] 2019-20',
       'Shared Time School [Public School] 2019-20',
       'Urban-centric Locale [Public School] 2019-20',
       'Total Students All Grades (Excludes AE) [Public School] 2019-20',
       'Full-Time Equivalent (FTE) Teachers [Public School] 2019-20',
       'Pupil/Teacher Ratio [Public School] 2019-20'],
      dtype='object')

In [23]:
school_data = school_data.drop('__id_left', axis=1)

school_data = school_data.drop('__id_right', axis=1)

NameError: name 'school_data' is not defined

NameError: name 'school_data' is not defined

In [26]:
left_on = ['Incident_ID']
right_on = ['Incident_ID']
master_df = fuzzymatcher.fuzzy_left_join(school_data,irp_data,left_on,right_on)

In [32]:
master_df.columns

Index(['best_match_score', '__id_left', '__id_right', 'best_match_score',
       'School Name', 'School_left', 'State_left',
       'State Abbr [Public School] Latest available year', 'Incident_ID_left',
       'Month_left',
       ...
       'Bullied_right', 'Domestic_Violence_right', 'Gang_Related_right',
       'Active_Shooter_FBI_right', 'Shots_Fired_right', 'LAT_right',
       'LNG_right', 'NCESSCH', 'IPR_EST', 'IPR_SE'],
      dtype='object', length=102)

In [29]:
import pandas as pd
left_on = ['Incident_ID_left']
right_on = ['Incident_ID']
df_ryan = pd.read_csv('/home/jklingl/Downloads/school_safety_2.csv')
master_df = pd.read_csv('/home/jklingl/capstone/master_school_df.csv')

In [30]:
master_df = master_df.drop('__id_left', axis=1)

master_df = master_df.drop('__id_right', axis=1)

In [31]:
final_df = fuzzymatcher.fuzzy_left_join(master_df,df_ryan,left_on,right_on)

In [33]:
final_df.to_csv('latest_school_safety_df.csv',index=False)

In [24]:
master_df.to_csv('master_school_df.csv', index=False)

In [6]:
# matching the zipcodes with the initial df
df_zips = pd.read_csv('/home/jklingl/capstone/zipcodes.csv')
df_schools = pd.read_csv('/home/jklingl/capstone/schools_only.csv')
left_on = ['School']
right_on = ['School']
BIG_DF = fuzzymatcher.fuzzy_left_join(df_zips,df_schools,left_on,right_on)

In [11]:
BIG_DF.to_csv('big_data_nces.csv', index=False)

## Below working on megring nces data with master data frame

In [3]:
df = pd.read_csv('/home/jklingl/Downloads/school_safety_all_finance.csv')
df_nces = pd.read_csv('/home/jklingl/capstone/nces_data/nces_final_clean.csv')

/home/jklingl/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3398: DtypeWarning: Columns (40,190,597,601,607,609,617,619,639,646) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [8]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Incident_ID,Month,Day,Year,Date,School,Victims_Killed,...,Ancestry_Puget_Sound_Salish,Immigration_Uzbekistan,Ancestry_Taiwanese,Ancestry_Menominee,Ancestry_Tsimshian,Immigration_Azores,Ancestry_Fijian,Ancestry_Yakama,Ancestry_Soviet_Union,Immigration_Cabo_Verde
0,0,0,0,20231103INKII,11,3,2023,11/3/2023,Kipp Indy Legacy High School,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,1,20231102NCFRM,11,2,2023,11/2/2023,Freedom High School,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2,2,20231102OHWAL,11,2,2023,11/2/2023,Washington Elementary School,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,3,3,20231030NCRAR,10,30,2023,10/30/2023,Raleigh School Bus,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,4,4,20231027TXDUS,10,27,2023,10/27/2023,Dub Farris Athletic Complex,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2567,2567,2567,2567,19660427NYBAB,4,27,1966,4/27/1966,Bay Shore High School,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2568,2568,2568,2568,19660328CAJOL,3,28,1966,3/28/1966,Jordan High School,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2569,2569,2569,2569,19660324CACAM,3,24,1966,3/24/1966,Camino Pablo Elementary School,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2570,2570,2570,2570,19660314TXCAW,3,14,1966,3/14/1966,Carver High School,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2571,2571,2571,2571,19660311NCIRC,3,11,1966,3/11/1966,Irwing Avenue Junior High School,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df_nces

,School Name,District Name,Mailing Address,Type,Supervisory Union #,Total Students:,Classroom Teachers (FTE):,Student/Teacher Ratio:,NCES School ID,State School ID,...,Grade KG,Grade 1,Grade 2,Grade 3,Grade 4,Grade 5,Grade 6,Grade 7,Grade 8,State
0,KIPP Indy Legacy High,Kipp Indy Legacy Highdistrict information,"2255 N Ralston AveIndianapolis, IN 46218",Regular school,NaN,377,27.00,13.96,180020602669,IN-9135-9138,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IN
1,Freedom High,Burke County Schoolsdistrict information,"511 Independence BoulevardMorganton, NC 28655",Regular school,NaN,"1,414",73.62,19.21,370048000176,NC-120-318,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NC
2,Washington Elementary School,Lorain Citydistrict information,"1025 W 23rd StLorain, OH 44052-4615",Regular school,NaN,259,17.00,15.24,390442601203,OH-044263-039347,...,34.0,39.0,37.0,29.0,41.0,47.0,NaN,NaN,NaN,OH
3,Donaldsonville High School,Ascension Parishdistrict information,"100 Tiger DriveDonaldsonville, LA 70734",Regular school,NaN,435,39.86,10.91,220009000036,LA-003-003003,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LA
4,Carver Vocational-Technical High,Baltimore City Public Schoolsdistrict information,"2201 Presstman StreetBaltimore, MD 21216-4106",Vocational school,NaN,"1,020",55.50,18.38,240009000168,MD-30-300454,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1954,Sousa MS,District Of Columbia Public Schoolsdistrict in...,"3650 ELY PL. SEWashington, DC 20019",Regular school,NaN,215,23.50,9.15,110003000019,DC-001-427,...,NaN,NaN,NaN,NaN,NaN,NaN,70.0,78.0,67.0,DC
1955,Tomah Middle,Tomah Area School Districtdistrict information,"612 Hollister AveTomah, WI 54660-1960",Regular school,NaN,676,47.22,14.32,551491001938,WI-5747-0160,...,NaN,NaN,NaN,NaN,NaN,NaN,202.0,226.0,248.0,WI
1956,Hanes Magnet School,Winston Salem / Forsyth County Schoolsdistrict...,"2355 Pleasant StWinston Salem, NC 27107",Regular school,NaN,906,52.27,17.33,370150000608,NC-340-392,...,NaN,NaN,NaN,NaN,NaN,NaN,320.0,292.0,294.0,NC
1957,The Academy @ Shawnee,Jefferson Countydistrict information,"4001 Herman StreetLouisville, KY 40212",Regular school,NaN,532,40.00,13.30,210299000777,KY-056275000-056275590,...,NaN,NaN,NaN,NaN,NaN,NaN,36.0,38.0,33.0,KY
1958,Statesville High,Iredell-statesville Schoolsdistrict information,"474 N Center StStatesville, NC 28677-4022",Regular school,NaN,879,56.30,15.61,370231002303,NC-490-354,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NC

In [11]:
pd.merge(df, df_nces, left_on=['School','State'],right_on=['School Name','State'], how='inner')

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Incident_ID,Month,Day,Year,Date,School,Victims_Killed,...,Grade PK,Grade KG,Grade 1,Grade 2,Grade 3,Grade 4,Grade 5,Grade 6,Grade 7,Grade 8
0,2,2,2,20231102OHWAL,11,2,2023,11/2/2023,Washington Elementary School,0,...,32.0,34.0,39.0,37.0,29.0,41.0,47.0,NaN,NaN,NaN
1,5,5,5,20231027LADOD,10,27,2023,10/27/2023,Donaldsonville High School,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,7,7,7,20231027MIDED,10,26,2023,10/26/2023,Denby High School,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1967,1967,1967,19950327MIDED,3,27,1995,3/27/1995,Denby High School,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16,16,16,20231019WAEVV,10,19,2023,10/19/2023,Evergreen High School,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,2471,2471,2471,19731023OHBAB,10,23,1973,10/23/1973,Barberton High School,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
536,2491,2491,2491,19720505INDEI,5,5,1972,5/5/1972,Decatur Central High School,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
537,2515,2515,2515,19710527MIBES,5,27,1971,5/27/1971,Benton Harbor High School,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
538,2528,2528,2528,19700928IACED,9,28,1970,9/28/1970,Central High School,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
539,2559,2559,2559,19670503ILWEN,5,3,1967,5/3/1967,West Leyden High School,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
left_on = ['School','State']
right_on = ['School Name','State']
df_fuzz = fuzzymatcher.fuzzy_left_join(df_zips,df_schools,left_on,right_on)

NameError: name 'df_zips' is not defined